# ---------------------------------------------------------------------------- #
#                             GATEWAY CONFIGURATION                            #
# ---------------------------------------------------------------------------- #
server:
  port: 8080
# ---------------------------------------------------------------------------- #
#                             EUREKA CONFIGURATIONS                            #
# ---------------------------------------------------------------------------- #
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
  instance:
    hostname: localhost
# ---------------------------------------------------------------------------- #
#                             SPRING CONFIGURATIONS                            #
#                             ROUTES OF THE GATEWAY                            #
# ---------------------------------------------------------------------------- #
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: follow-service
          uri: lb://follow-service
          predicates:
            - Path=/follows/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/posts/**, /hashtags/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/bookmarks/**, /qualifications/**, /comments/**
