# ---------------------------------------------------------------------------- #
#                           APPLICATION CONFIGURATION                          #
# ---------------------------------------------------------------------------- #
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always
# ---------------------------------------------------------------------------- #
#                         TO SEE H2 CONSOLE IN BROWSER:                        #
#                       http://localhost:8091/h2-console                       #
#                              ENABLING H2 CONSOLE                             #
# ---------------------------------------------------------------------------- #
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  # ---------------------------------------------------------------------------- #
  #                                   DATABASE                                   #
  # ---------------------------------------------------------------------------- #
  datasource:
    url: jdbc:h2:mem:userDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: Hugo
    password: Rushia
  # ---------------------------------------------------------------------------- #
  #                                JPA / HIBERNATE                               #
  # ---------------------------------------------------------------------------- #
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
# ---------------------------------------------------------------------------- #
#                             LOGGING CONFIGURATION                            #
# ---------------------------------------------------------------------------- #
Logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# ---------------------------------------------------------------------------- #
#                             EUREKA CONFIGURATION                             #
# ---------------------------------------------------------------------------- #
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
  instance:
    hostname: localhost
# ---------------------------------------------------------------------------- #
#                           MANAGEMENT CONFIGURATION                           #
# ---------------------------------------------------------------------------- #
management:
  endpoints:
    web:
      exposure:
        include: "*"
