server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/Distopya/Microservice
          search-paths: config-data
  #          username: ${GIT_USER}
  #          password: ${GIT_PASSWORD}
#  security:
#    user:
#      name: Hugo
#      password: Rushia
  application:
    name: config-server